services:
  - type: web
    name: nl2pd-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python run_backend.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: PORT
        value: 8000
    healthCheckPath: /health